const db=window.supabase.createClient('https://xiziwoquiatlpkihkdoh.supabase.co','sb_publishable_3TmqRI06OhjnXkxelxDwWQ__YsvBgXQ');let items=[],episodes=[],sources={},orders=[];const $=x=>document.getElementById(x),esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
async function enter(user){const {data}=await db.from('admins').select('user_id').eq('user_id',user.id).maybeSingle();if(!data){await db.auth.signOut();$('loginMsg').textContent='គណនីនេះមិនមានសិទ្ធិ Admin ទេ';return}$('login').classList.add('hide');$('app').classList.remove('hide');await loadAll()}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginMsg').textContent='កំពុងចូល...';const {data,error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)$('loginMsg').textContent='Email ឬ Password មិនត្រឹមត្រូវ';else enter(data.user)};$('logout').onclick=()=>db.auth.signOut().then(()=>location.reload());
async function loadAll(){await Promise.all([loadCatalog(),loadOrders(),loadSettings()])}
async function loadCatalog(){let [a,b,c]=await Promise.all([db.from('idrama_items').select('*').order('created_at',{ascending:false}),db.from('idrama_episodes').select('*').order('number'),db.from('idrama_episode_sources').select('*')]);items=a.data||[];episodes=b.data||[];sources={};(c.data||[]).forEach(x=>sources[x.episode_id]=x.video_url);$('s1').textContent=items.length;$('s2').textContent=episodes.length;$('s3').textContent=items.filter(x=>x.paid).length;renderMovies();fillSelect();renderEps()}
function grad(a){return `linear-gradient(145deg,hsl(${a||340} 78% 58%),hsl(${((a||340)+38)%360} 76% 44%))`}function money(x){return x.currency==='KHR'?`${Number(x.price).toLocaleString()} ៛`:`$${Number(x.price).toFixed(2)}`}
function renderMovies(){let q=$('search').value.toLowerCase();let list=items.filter(x=>x.title.toLowerCase().includes(q));$('movieList').innerHTML=list.map(x=>`<div class="row">${x.poster?`<img class="thumb" src="${esc(x.poster)}">`:`<div class="thumb" style="background:${grad(x.accent)}"></div>`}<div><h3>${esc(x.title)}</h3><div class="meta">${esc(x.category)} · ${episodes.filter(e=>e.item_id===x.id).length} ភាគ · ${x.paid?money(x):'FREE'} ${x.published?'':'· Hidden'}</div></div><div class="r"><button class="btn soft" data-edit="${x.id}">កែ</button><button class="btn dark" data-ep="${x.id}">ភាគ</button><button class="btn danger" data-del="${x.id}">លុប</button></div></div>`).join('')||'<div class="muted">មិនទាន់មានរឿងទេ</div>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editMovie(b.dataset.edit));document.querySelectorAll('[data-ep]').forEach(b=>b.onclick=()=>{show('eps');$('movieSelect').value=b.dataset.ep;renderEps()});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>delMovie(b.dataset.del))}
function resetMovie(){$('movieForm').reset();$('mid').value='';$('word').value='DRAMA';$('accent').value=340;$('views').value=0;$('price').value=0;$('currency').value='USD';$('published').checked=true;$('movieMsg').textContent=''}$('newMovie').onclick=()=>{$('movieFormWrap').classList.remove('hide');resetMovie()};$('cancelMovie').onclick=()=>$('movieFormWrap').classList.add('hide');$('search').oninput=renderMovies;
function editMovie(id){let x=items.find(i=>i.id===id);$('mid').value=x.id;$('title').value=x.title;$('category').value=x.category;$('genre').value=x.genre;$('poster').value=x.poster;$('word').value=x.word;$('accent').value=x.accent;$('views').value=x.views;$('description').value=x.description;$('paid').checked=x.paid;$('price').value=x.price;$('currency').value=x.currency;$('featured').checked=x.featured;$('published').checked=x.published;$('movieFormWrap').classList.remove('hide');window.scrollTo({top:100,behavior:'smooth'})}
$('movieForm').onsubmit=async e=>{e.preventDefault();let p={title:$('title').value.trim(),category:$('category').value,genre:$('genre').value.trim(),poster:$('poster').value.trim(),word:$('word').value.trim()||'DRAMA',accent:+$('accent').value||340,views:+$('views').value||0,description:$('description').value.trim(),paid:$('paid').checked,price:+$('price').value||0,currency:$('currency').value,featured:$('featured').checked,published:$('published').checked,updated_at:new Date().toISOString()},id=$('mid').value,r=id?await db.from('idrama_items').update(p).eq('id',id):await db.from('idrama_items').insert(p);$('movieMsg').textContent=r.error?r.error.message:'រក្សាទុករួចរាល់ ✓';if(!r.error){await loadCatalog();setTimeout(()=>$('movieFormWrap').classList.add('hide'),350)}};
async function delMovie(id){let x=items.find(i=>i.id===id);if(!confirm('លុប '+x.title+' និងភាគ/Orders ទាំងអស់?'))return;await db.from('idrama_items').delete().eq('id',id);await loadAll()}
function fillSelect(){let old=$('movieSelect').value;$('movieSelect').innerHTML=items.map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join('');if(items.some(x=>x.id===old))$('movieSelect').value=old}$('movieSelect').onchange=renderEps;
function renderEps(){let id=$('movieSelect').value,list=episodes.filter(e=>e.item_id===id);$('epList').innerHTML=list.map(e=>`<div class="row"><div class="thumb" style="height:54px;display:grid;place-items:center;background:#101620;color:#fff;font-weight:800">${e.number}</div><div><h3>${esc(e.title||('ភាគ '+e.number))}</h3><div class="meta">${esc(e.duration)} ${sources[e.id]?'· Video ✓':'· No video'} ${e.preview?'· Preview':''}</div></div><div class="r"><button class="btn soft" data-eedit="${e.id}">កែ</button><button class="btn danger" data-edel="${e.id}">លុប</button></div></div>`).join('')||'<div class="muted">មិនទាន់មានភាគទេ</div>';document.querySelectorAll('[data-eedit]').forEach(b=>b.onclick=()=>editEp(b.dataset.eedit));document.querySelectorAll('[data-edel]').forEach(b=>b.onclick=()=>delEp(b.dataset.edel))}
function resetEp(){$('epForm').reset();$('eid').value='';$('epp').checked=true;$('epMsg').textContent=''}$('cancelEp').onclick=resetEp;
function editEp(id){let e=episodes.find(x=>x.id===id);$('eid').value=e.id;$('movieSelect').value=e.item_id;$('epn').value=e.number;$('ept').value=e.title;$('epd').value=e.duration;$('epv').value=sources[e.id]||'';$('eppreview').checked=e.preview;$('epp').checked=e.published}
$('epForm').onsubmit=async e=>{e.preventDefault();let id=$('eid').value,p={item_id:$('movieSelect').value,number:+$('epn').value,title:$('ept').value.trim(),duration:$('epd').value.trim(),preview:$('eppreview').checked,published:$('epp').checked,updated_at:new Date().toISOString()},r;if(id)r=await db.from('idrama_episodes').update(p).eq('id',id).select('id').single();else r=await db.from('idrama_episodes').insert(p).select('id').single();if(r.error){$('epMsg').textContent=r.error.message;return}let eid=id||r.data.id;let url=$('epv').value.trim();let sr=await db.from('idrama_episode_sources').upsert({episode_id:eid,video_url:url,updated_at:new Date().toISOString()});$('epMsg').textContent=sr.error?sr.error.message:'រក្សាទុករួចរាល់ ✓';if(!sr.error){await loadCatalog();resetEp()}};
async function delEp(id){if(!confirm('លុបភាគនេះ?'))return;await db.from('idrama_episodes').delete().eq('id',id);await loadCatalog()}
async function loadOrders(){let r=await db.from('idrama_orders').select('*').order('created_at',{ascending:false});orders=r.data||[];$('s4').textContent=orders.filter(x=>x.status==='pending').length;renderOrders()}
function renderOrders(){$('orderList').innerHTML=orders.map(o=>{let item=items.find(x=>x.id===o.item_id);return `<div class="row"><div class="thumb" style="height:54px;display:grid;place-items:center;background:#101620">$</div><div><h3>${esc(item?.title||'Unknown movie')}</h3><div class="meta">${esc(o.order_code)} · ${esc(o.buyer_email)} · ${o.currency==='KHR'?Number(o.amount).toLocaleString()+' ៛':'$'+Number(o.amount).toFixed(2)}</div><span class="status ${o.status}">${o.status.toUpperCase()}</span></div><div class="r">${o.status==='pending'?`<button class="btn pink" data-paid="${o.id}">Mark Paid</button><button class="btn danger" data-cancel="${o.id}">Cancel</button>`:''}</div></div>`}).join('')||'<div class="muted">មិនទាន់មាន Order ទេ</div>';document.querySelectorAll('[data-paid]').forEach(b=>b.onclick=()=>setOrder(b.dataset.paid,'paid'));document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>setOrder(b.dataset.cancel,'cancelled'))}
async function setOrder(id,status){let p={status,paid_at:status==='paid'?new Date().toISOString():null};let r=await db.from('idrama_orders').update(p).eq('id',id);if(r.error)alert(r.error.message);await loadOrders()}
$('refreshOrders').onclick=loadOrders;
async function loadSettings(){let r=await db.from('site_settings').select('*').eq('id',1).single();if(r.data){$('qrUrl').value=r.data.bakong_qr_url||'';$('paymentNote').value=r.data.payment_note||''}}
$('settingsForm').onsubmit=async e=>{e.preventDefault();let r=await db.from('site_settings').update({bakong_qr_url:$('qrUrl').value.trim(),payment_note:$('paymentNote').value.trim(),updated_at:new Date().toISOString()}).eq('id',1);$('settingsMsg').textContent=r.error?r.error.message:'រក្សាទុករួចរាល់ ✓'};
function show(name){['movies','eps','orders','settings'].forEach(x=>$(x).classList.toggle('hide',x!==name));[['tabMovies','movies'],['tabEps','eps'],['tabOrders','orders'],['tabSettings','settings']].forEach(([b,s])=>$(b).className='btn '+(s===name?'active':'soft'));if(name==='eps'){fillSelect();renderEps()}if(name==='orders')loadOrders()}
$('tabMovies').onclick=()=>show('movies');$('tabEps').onclick=()=>show('eps');$('tabOrders').onclick=()=>show('orders');$('tabSettings').onclick=()=>show('settings');
(async()=>{let {data:{session}}=await db.auth.getSession();if(session)enter(session.user)})();