const db=window.supabase.createClient('https://xiziwoquiatlpkihkdoh.supabase.co','sb_publishable_3TmqRI06OhjnXkxelxDwWQ__YsvBgXQ');
let all=[],filter='all',query='',currentMovie=null,currentOrder=null,pollTimer=null,settings={bakong_qr_url:'',payment_note:''};
const $=x=>document.getElementById(x),esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
function grad(a){a=+a||340;return `linear-gradient(145deg,hsl(${a} 78% 58%),hsl(${(a+38)%360} 76% 44%))`}
function cats(x){let g=(x.genre||'').toLowerCase(),c=[x.category];if(g.includes('ស្នេហា')||g.includes('romance'))c.push('romance');if(g.includes('កើតឡើងវិញ')||g.includes('reborn'))c.push('reborn');if(g.includes('បុរាណ')||g.includes('ancient'))c.push('ancient');if(g.includes('គ្រួសារ')||g.includes('family'))c.push('family');return c}
function money(x){if(!x.paid)return 'FREE';return x.currency==='KHR'?`${Number(x.price).toLocaleString()} ៛`:`$${Number(x.price).toFixed(2)}`}
function posterMarkup(x,detail=false){if(x.poster&&/^https?:\/\//i.test(x.poster))return `<img src="${esc(x.poster)}" loading="lazy" alt="${esc(x.title)}">`;return `<div class="fill${detail?' detail-fill':''}" style="background:${grad(x.accent)}"><div class="word">${esc(x.word||'DRAMA')}</div></div>`}
function card(x){return `<article class="card" data-id="${x.id}"><div class="poster">${posterMarkup(x)}<span class="price ${x.paid?'':'free'}">${money(x)}</span></div><h3>${esc(x.title)}</h3></article>`}
function render(){let list=all.filter(x=>(filter==='all'||x.cats.includes(filter))&&x.title.toLowerCase().includes(query.toLowerCase()));$('grid').innerHTML=list.map(card).join('');$('empty').style.display=list.length?'none':'block';$('empty').textContent='រកមិនឃើញរឿងដែលត្រូវនឹងការស្វែងរកទេ។';document.querySelectorAll('[data-id]').forEach(e=>e.onclick=()=>openDrama(e.dataset.id))}
async function load(){let [a,s]=await Promise.all([db.from('idrama_items').select('*').eq('published',true).order('featured',{ascending:false}).order('created_at',{ascending:false}),db.from('site_settings').select('bakong_qr_url,payment_note').eq('id',1).maybeSingle()]);if(a.error){$('empty').textContent='មិនអាចទាញយកទិន្នន័យបាន';return}if(s.data)settings=s.data;all=(a.data||[]).map(x=>({...x,cats:cats(x)}));render()}
async function getEpisodes(itemId){let {data,error}=await db.from('idrama_episodes').select('id,number,preview,published').eq('item_id',itemId).eq('published',true).order('number');return error?[]:(data||[])}
async function getFreeTelegramLink(itemId){let eps=await getEpisodes(itemId),full=eps.filter(e=>!e.preview);if(!full.length)return '';let ids=full.map(e=>e.id);let {data}=await db.from('idrama_episode_sources').select('episode_id,video_url').in('episode_id',ids);let row=(data||[]).find(x=>/^(https?:\/\/)?(t\.me|telegram\.me|telegram\.dog)\//i.test(x.video_url||'')||/^tg:\/\//i.test(x.video_url||''));return row?.video_url||''}
function showBuyButton(x){$('buybox').className='buybox';$('buybox').innerHTML=`<div><b>${money(x)}</b><small>ទូទាត់ Bakong KHQR រួចបើក Telegram រឿងពេញ។</small></div><button id="buyBtn" class="btn pink">ទិញរឿង</button>`;$('buyBtn').onclick=()=>startPurchase(x)}
async function openDrama(id){let x=all.find(i=>String(i.id)===String(id));if(!x)return;currentMovie=x;$('dt').textContent=x.title;$('detailPoster').innerHTML=posterMarkup(x,true);$('story').textContent=(x.description||'').trim()||'មិនទាន់មានសេចក្ដីសង្ខេបសាច់រឿងទេ។';$('buybox').innerHTML='<div class="loadingline">កំពុងរៀបចំ...</div>';$('movieModal').classList.add('show');document.body.style.overflow='hidden';if(!x.paid){let tg=await getFreeTelegramLink(x.id);$('buybox').className='buybox owned';$('buybox').innerHTML=tg?`<div><b>FREE ✓</b><small>បើករឿងពេញក្នុង Telegram</small></div><a class="btn telegram" href="${esc(tg)}" target="_blank" rel="noopener noreferrer">បើក Telegram</a>`:`<div><b>FREE</b><small>Telegram Link មិនទាន់បានដាក់សម្រាប់រឿងនេះទេ។</small></div>`;return}if(typeof window.renderGuestPurchaseState==='function'){await window.renderGuestPurchaseState(x)}else showBuyButton(x)}
function closeMovie(){$('movieModal').classList.remove('show');document.body.style.overflow=''}
$('movieClose').onclick=closeMovie;
$('payClose').onclick=()=>{clearInterval(pollTimer);$('payModal').classList.remove('show')};
document.addEventListener('click',e=>{let b=e.target.closest('[data-f]');if(b){filter=b.dataset.f;document.querySelectorAll('[data-f]').forEach(x=>x.classList.toggle('active',x.dataset.f===filter));render()}});$('q').oninput=e=>{query=e.target.value.trim();render()};$('movieModal').onclick=e=>{if(e.target.id==='movieModal')closeMovie()};$('payModal').onclick=e=>{if(e.target.id==='payModal')$('payModal').classList.remove('show')};document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMovie();$('payModal').classList.remove('show')}});
load();
