const db=window.supabase.createClient('https://xiziwoquiatlpkihkdoh.supabase.co','sb_publishable_3TmqRI06OhjnXkxelxDwWQ__YsvBgXQ');
let all=[],filter='all',query='',session=null,currentMovie=null,currentOrder=null,pollTimer=null,settings={bakong_qr_url:'',payment_note:''};
const $=x=>document.getElementById(x),esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
function grad(a){a=+a||340;return `linear-gradient(145deg,hsl(${a} 78% 58%),hsl(${(a+38)%360} 76% 44%))`}
function cats(x){let g=(x.genre||'').toLowerCase(),c=[x.category];if(g.includes('ស្នេហា')||g.includes('romance'))c.push('romance');if(g.includes('កើតឡើងវិញ')||g.includes('reborn'))c.push('reborn');if(g.includes('បុរាណ')||g.includes('ancient'))c.push('ancient');if(g.includes('គ្រួសារ')||g.includes('family'))c.push('family');return c}
function fmt(n){n=+n||0;if(n>=1e6)return(n/1e6).toFixed(1).replace('.0','')+'M';if(n>=1e3)return(n/1e3).toFixed(1).replace('.0','')+'K';return''+n}
function money(x){if(!x.paid)return 'FREE';return x.currency==='KHR'?`${Number(x.price).toLocaleString()} ៛`:`$${Number(x.price).toFixed(2)}`}
function card(x){let v=x.poster&&/^https?:\/\//i.test(x.poster)?`<img src="${esc(x.poster)}" loading="lazy" alt="${esc(x.title)}">`:`<div class="fill" style="background:${grad(x.accent)}"><div class="word">${esc(x.word||'DRAMA')}</div></div>`;return `<article class="card" data-id="${x.id}"><div class="poster">${v}<span class="badge">${x.eps} ភាគ</span>${x.paid?`<span class="price">${money(x)}</span>`:''}</div><h3>${esc(x.title)}</h3><div class="meta">${esc(({ai:'AI Drama',live:'រឿងមនុស្ស',anime:'រឿងគំនូរ'})[x.category]||x.category)}${x.genre?' · '+esc(x.genre):''}</div></article>`}
function render(){let list=all.filter(x=>(filter==='all'||x.cats.includes(filter))&&x.title.toLowerCase().includes(query.toLowerCase()));$('grid').innerHTML=list.map(card).join('');$('empty').style.display=list.length?'none':'block';$('empty').textContent='រកមិនឃើញរឿងដែលត្រូវនឹងការស្វែងរកទេ។';$('aigrid').innerHTML=all.filter(x=>x.category==='ai').slice(0,6).map(card).join('');$('rank').innerHTML=all.slice().sort((a,b)=>b.views-a.views).slice(0,8).map((x,i)=>`<div class="rr" data-id="${x.id}"><div class="num">${String(i+1).padStart(2,'0')}</div><div class="th" style="background:${grad(x.accent)}"></div><div><div class="rname">${esc(x.title)}</div><div class="meta">${x.eps} ភាគ · ${money(x)}</div></div><div class="views">${fmt(x.views)} views</div></div>`).join('');document.querySelectorAll('[data-id]').forEach(e=>e.onclick=()=>openDrama(e.dataset.id))}
async function load(){let [a,b,s]=await Promise.all([db.from('idrama_items').select('*').order('featured',{ascending:false}).order('created_at',{ascending:false}),db.from('idrama_episodes').select('item_id,number').eq('published',true),db.from('site_settings').select('bakong_qr_url,payment_note').eq('id',1).maybeSingle()]);if(a.error){$('empty').textContent='មិនអាចទាញយកទិន្នន័យបាន';return}if(s.data)settings=s.data;let c={};(b.data||[]).forEach(e=>c[e.item_id]=(c[e.item_id]||0)+1);all=(a.data||[]).map(x=>({...x,eps:c[x.id]||0,cats:cats(x)}));render()}
async function hasPaidAccess(itemId){if(!session)return false;let {data}=await db.from('idrama_orders').select('id,status').eq('item_id',itemId).eq('status','paid').limit(1);return !!data?.length}
async function openDrama(id){let x=all.find(i=>i.id===id);if(!x)return;currentMovie=x;$('dt').textContent=x.title;$('tags').innerHTML=`<span class="tag">${esc(x.category)}</span>${x.genre?`<span class="tag">${esc(x.genre)}</span>`:''}<span class="tag">${x.eps} ភាគ</span>${x.paid?`<span class="tag">${money(x)}</span>`:'<span class="tag">FREE</span>'}`;$('desc').textContent=x.description||'';resetVideo();$('episodes').innerHTML='<span class="meta">កំពុងទាញយក...</span>';$('buybox').classList.add('hide');$('movieModal').classList.add('show');document.body.style.overflow='hidden';let access=!x.paid||await hasPaidAccess(id);let {data,error}=await db.from('idrama_episodes').select('*').eq('item_id',id).eq('published',true).order('number');if(error||!data?.length){$('episodes').innerHTML='<span class="meta">មិនទាន់មានភាគទេ។</span>';return}if(x.paid){$('buybox').classList.remove('hide');$('buybox').className='buybox '+(access?'owned':'');$('buybox').innerHTML=access?`<div><b>បានទិញរួច ✓</b><small>អ្នកអាចមើលភាគទាំងអស់បានហើយ</small></div>`:`<div><b>${money(x)}</b><small>ទិញម្តង មើលរឿងពេញបាន</small></div><button id="buyBtn" class="btn pink">ទិញរឿងពេញ</button>`;if(!access)$('buyBtn').onclick=()=>startPurchase(x)}$('episodes').innerHTML=data.map((e,i)=>{let can=access||e.preview;return `<button class="ep ${i===0&&can?'active':''} ${can?'':'locked'}" data-eid="${e.id}" data-can="${can?'1':'0'}">${e.number}${can?'':' 🔒'}</button>`}).join('');$('episodes').querySelectorAll('.ep').forEach(b=>b.onclick=()=>playEpisode(b));let first=$('episodes').querySelector('[data-can="1"]');if(first)first.click()}
function resetVideo(){$('video').innerHTML='<button id="movieClose" class="close">×</button><div class="play">▶</div>';$('movieClose').onclick=closeMovie}
async function playEpisode(b){if(b.dataset.can!=='1'){if(!session){openAuth('login');return}if(currentMovie)startPurchase(currentMovie);return}document.querySelectorAll('.ep').forEach(x=>x.classList.remove('active'));b.classList.add('active');let {data,error}=await db.from('idrama_episode_sources').select('video_url').eq('episode_id',b.dataset.eid).maybeSingle();if(error||!data?.video_url){resetVideo();return}let u=data.video_url;if(/^https?:\/\//i.test(u)){$('video').innerHTML=`<button id="movieClose" class="close">×</button><video controls autoplay playsinline src="${esc(u)}"></video>`;$('movieClose').onclick=closeMovie}else resetVideo()}
function closeMovie(){$('movieModal').classList.remove('show');document.body.style.overflow='';let v=$('video').querySelector('video');if(v)v.pause()}
function openAuth(tab='login'){$('authModal').classList.add('show');switchAuth(tab)}
function switchAuth(tab){let login=tab==='login';$('loginForm').classList.toggle('hide',!login);$('registerForm').classList.toggle('hide',login);$('loginTab').className='btn '+(login?'pink':'dark');$('registerTab').className='btn '+(!login?'pink':'dark');$('authMsg').textContent='';$('authMsg').className='msg'}
$('loginTab').onclick=()=>switchAuth('login');$('registerTab').onclick=()=>switchAuth('register');$('authBtn').onclick=()=>openAuth('login');$('authClose').onclick=()=>$('authModal').classList.remove('show');$('logoutBtn').onclick=async()=>{await db.auth.signOut();session=null;updateAccount();if(currentMovie)openDrama(currentMovie.id)};
$('loginForm').onsubmit=async e=>{e.preventDefault();$('authMsg').textContent='កំពុងចូល...';const {data,error}=await db.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(error){$('authMsg').className='msg err';$('authMsg').textContent='Email ឬ Password មិនត្រឹមត្រូវ';return}session=data.session;$('authModal').classList.remove('show');updateAccount();if(currentMovie)openDrama(currentMovie.id)};
$('registerForm').onsubmit=async e=>{e.preventDefault();$('authMsg').textContent='កំពុងបង្កើតគណនី...';let name=$('regName').value.trim(),phone=$('regPhone').value.trim();const {data,error}=await db.auth.signUp({email:$('regEmail').value.trim(),password:$('regPassword').value,options:{data:{full_name:name,phone}}});if(error){$('authMsg').className='msg err';$('authMsg').textContent=error.message;return}if(data.session){session=data.session;$('authModal').classList.remove('show');updateAccount()}else{$('authMsg').className='msg';$('authMsg').textContent='បានបង្កើតគណនី។ សូមពិនិត្យ Email ដើម្បីបញ្ជាក់គណនី។'}};
function updateAccount(){let on=!!session;$('authBtn').classList.toggle('hide',on);$('logoutBtn').classList.toggle('hide',!on);$('userPill').classList.toggle('hide',!on);$('userPill').textContent=on?(session.user.user_metadata?.full_name||session.user.email):''}
async function startPurchase(x){if(!session){openAuth('login');return}let {data:paid}=await db.from('idrama_orders').select('*').eq('item_id',x.id).eq('status','paid').limit(1);if(paid?.length){openDrama(x.id);return}let {data:pending}=await db.from('idrama_orders').select('*').eq('item_id',x.id).eq('status','pending').order('created_at',{ascending:false}).limit(1);let order=pending?.[0];if(!order){let user=session.user;let payload={user_id:user.id,item_id:x.id,amount:x.price,currency:x.currency,status:'pending',payment_method:'aba_payway_khqr',buyer_name:user.user_metadata?.full_name||'',buyer_email:user.email||'',buyer_phone:user.user_metadata?.phone||''};let r=await db.from('idrama_orders').insert(payload).select('*').single();if(r.error){alert(r.error.message);return}order=r.data}currentOrder=order;showPayment(order,x);startPolling(order.id,x.id)}
function showPayment(order,x){$('payModal').classList.add('show');let qr=settings.bakong_qr_url?`<img class="qr" src="${esc(settings.bakong_qr_url)}" alt="KHQR">`:`<div class="paymeta" style="text-align:center;margin:16px 0">KHQR/PayWay Merchant មិនទាន់បានភ្ជាប់ API ទេ។ Admin អាចដាក់ QR fallback ក្នុង Payment Settings។</div>`;$('payContent').innerHTML=`<div class="paymeta"><div>រឿង: <b>${esc(x.title)}</b></div><div>តម្លៃ: <b>${money(x)}</b></div><div>Order: <b>${esc(order.order_code)}</b></div></div>${qr}<div class="paymeta">${esc(settings.payment_note||'ស្កេន KHQR ហើយប្រព័ន្ធនឹងបើករឿងដោយស្វ័យប្រវត្តិ ពេលទូទាត់បានបញ្ជាក់។')}</div><button id="checkPay" class="btn soft" style="width:100%;margin-top:12px">ពិនិត្យការទូទាត់</button>`;$('payStatus').className='waiting';$('payStatus').textContent='កំពុងរង់ចាំការទូទាត់...';$('checkPay').onclick=()=>checkOrder(order.id,x.id)}
function startPolling(orderId,itemId){clearInterval(pollTimer);pollTimer=setInterval(()=>checkOrder(orderId,itemId),3500)}
async function checkOrder(orderId,itemId){let {data,error}=await db.from('idrama_orders').select('status').eq('id',orderId).maybeSingle();if(error||!data)return;if(data.status==='paid'){clearInterval(pollTimer);$('payStatus').className='success';$('payStatus').textContent='ទូទាត់ជោគជ័យ ✓ កំពុងបើករឿងពេញ...';setTimeout(()=>{$('payModal').classList.remove('show');openDrama(itemId)},900)}else if(['cancelled','failed'].includes(data.status)){clearInterval(pollTimer);$('payStatus').className='msg err';$('payStatus').textContent='ការទូទាត់មិនបានជោគជ័យ។'}}
$('payClose').onclick=()=>{clearInterval(pollTimer);$('payModal').classList.remove('show')};
document.addEventListener('click',e=>{let b=e.target.closest('[data-f]');if(b){filter=b.dataset.f;document.querySelectorAll('[data-f]').forEach(x=>x.classList.toggle('active',x.dataset.f===filter));render()}});$('q').oninput=e=>{query=e.target.value.trim();render()};$('movieModal').onclick=e=>{if(e.target.id==='movieModal')closeMovie()};$('authModal').onclick=e=>{if(e.target.id==='authModal')$('authModal').classList.remove('show')};$('payModal').onclick=e=>{if(e.target.id==='payModal')$('payModal').classList.remove('show')};document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMovie();$('authModal').classList.remove('show');$('payModal').classList.remove('show')}});
(async()=>{let {data:{session:s}}=await db.auth.getSession();session=s;updateAccount();db.auth.onAuthStateChange((event,sess)=>{session=sess;updateAccount()});await load()})();